package day_42_Exceptions;

public class ThrowsKeywords2 {
    public static void main(String[] args) throws ArithmeticException{

       // System.out.println("Test started");
       // System.out.println(8/0);
       // System.out.println("Test completed");
    }

}
